language: java

branches:
  only:
    - master

sudo: required

services:
  - docker

jobs:
  script:
    - docker build -t peopleapi .
  after_success:
    - docker login -u $docker-user -p $docker-password
    - docker tag front $docker-user/peopleapi:$TRAVIS_BUILD_NUMBER
    - docker push $docker-user/peopleapi:$TRAVIS_BUILD_NUMBER
    - docker tag front $docker-user/peopleapi:latest
    - docker push $docker-user/paopleapi:latest


