language: java

branches:
  only:
    - master

sudo: required

services:
  - docker

jobs:
  script:
    - docker build -t peepsapi .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag peepsapi $DOCKER_USER/peepsapi:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USER/peepsapi:$TRAVIS_BUILD_NUMBER
    - docker tag front $DOCKER_USER/peepsapi:latest
    - docker push $DOCKER_USER/peepseapi:latest


