language: java

branches:
  only:
    - master

sudo: required

services:
  - docker

jobs:
  script:
    - docker build -t peopleapi .
  after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag front $DOCKER_USER/peopleapi:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USER/peopleapi:$TRAVIS_BUILD_NUMBER
    - docker tag front $DOCKER_USER/peopleapi:latest
    - docker push $DOCKER_USER/paopleapi:latest


